import Testing
@testable import PoPCore

// M3: tile classification.
//
// The expected bitmask for every one of the 33 kinds was generated by running the
// JavaScript predicates from reference/PrinceJS/src/tiles/Base.js over the full range,
// so this is a differential test against the reference rather than a restatement of the
// Swift implementation.
//
//   bit 0 walkable   bit 1 space     bit 2 barrier    bit 3 freeFallBarrier
//   bit 4 barrierLeft bit 5 barrierRight bit 6 dangerous bit 7 safeWalkable
//   bit 8 jumpSpace  bit 9 exitDoor

private let expectedMasks: [(TileKind, Int)] = [
    (.space, 258), (.floor, 129), (.spikes, 129), (.pillar, 129), (.gate, 173),
    (.stuckButton, 129), (.dropButton, 129), (.tapestry, 165), (.bottomBigPillar, 129),
    (.topBigPillar, 258), (.potion, 129), (.looseBoard, 65), (.tapestryTop, 38),
    (.mirror, 157), (.debris, 129), (.raiseButton, 129), (.exitLeft, 641),
    (.exitRight, 641), (.chopper, 65), (.torch, 129), (.wall, 28), (.skeleton, 129),
    (.sword, 129), (.balconyLeft, 129), (.balconyRight, 129), (.latticePillar, 129),
    (.latticeSupport, 258), (.smallLattice, 258), (.latticeLeft, 258),
    (.latticeRight, 258), (.torchWithDebris, 129), (.debrisOnly, 129), (.null, 129),
]

private func mask(_ kind: TileKind) -> Int {
    var value = 0
    if kind.isWalkable { value |= 1 }
    if kind.isSpace { value |= 2 }
    if kind.isBarrier { value |= 4 }
    if kind.isFreeFallBarrier { value |= 8 }
    if kind.isBarrierLeft { value |= 16 }
    if kind.isBarrierRight { value |= 32 }
    if kind.isDangerousWalkable { value |= 64 }
    if kind.isSafeWalkable { value |= 128 }
    if kind.isJumpSpace { value |= 256 }
    if kind.isExitDoor { value |= 512 }
    return value
}

@Test(arguments: expectedMasks)
func tilePredicatesMatchTheReference(kind: TileKind, expected: Int) {
    #expect(mask(kind) == expected, "\(kind): got \(mask(kind)), expected \(expected)")
}

@Test func everyTileKindIsCovered() {
    #expect(expectedMasks.count == TileKind.allCases.count)
    #expect(Set(expectedMasks.map(\.0)) == Set(TileKind.allCases))
}

@Test func thePredicateSetsHaveTheReferenceSizes() {
    // From the JS: 25 walkable, 7 space, 5 barriers, 23 safe-walkable out of 33.
    #expect(TileKind.allCases.filter(\.isWalkable).count == 25)
    #expect(TileKind.allCases.filter(\.isSpace).count == 7)
    #expect(TileKind.allCases.filter(\.isBarrier).count == 5)
    #expect(TileKind.allCases.filter(\.isSafeWalkable).count == 23)
}

@Test func walkableIsNotTheComplementOfSpace() {
    // The easy mistake is to assume these partition the kinds. They do not.
    // `topBigPillar` is neither walkable nor space.
    #expect(!TileKind.topBigPillar.isWalkable)
    #expect(TileKind.topBigPillar.isSpace)
    // `floor` is walkable but not space.
    #expect(TileKind.floor.isWalkable)
    #expect(!TileKind.floor.isSpace)
    // `tapestryTop` is space AND a barrier, but not walkable, and NOT jump space.
    #expect(TileKind.tapestryTop.isSpace)
    #expect(TileKind.tapestryTop.isBarrier)
    #expect(!TileKind.tapestryTop.isJumpSpace)
    #expect(TileKind.tapestryTop.isBarrierRight)
    #expect(!TileKind.tapestryTop.isBarrierLeft)
}

@Test func tapestryIsABarrierForWalkingButNotForFalling() {
    // A hanging is solid to walk into but you fall straight past it.
    #expect(TileKind.tapestry.isBarrier)
    #expect(!TileKind.tapestry.isFreeFallBarrier)
    #expect(TileKind.tapestryTop.isBarrier)
    #expect(!TileKind.tapestryTop.isFreeFallBarrier)
    #expect(TileKind.mirror.isFreeFallBarrier)
    #expect(TileKind.gate.isFreeFallBarrier)
}
